# ======================
# Build Stage
# ======================

FROM eclipse-temurin:21-jdk AS build

WORKDIR /project

COPY . .

RUN chmod +x gradlew

RUN ./gradlew :app:bootJar --no-daemon

# ======================
# Runtime Stage
# ======================

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /project/app/build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]