services:

  db:
    image: postgres:latest
    container_name: salesrep-db
    restart: unless-stopped
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      POSTGRES_DB: salesrep_new
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

    ports:
      - "127.0.0.1:5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend

    container_name: salesrep-api

    restart: unless-stopped

    depends_on:
      - db

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/salesrep_new
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend

    container_name: salesrep-web

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "3000:80"

volumes:
  postgres_data:
