-- V21__add_grupo_to_produto.sql
-- Adiciona a coluna 'grupo' na tabela produto e popula com 'Nome Classe Prod.' do CSV.

ALTER TABLE produto ADD COLUMN IF NOT EXISTS grupo VARCHAR(255);

-- Atualizar o grupo para cada produto com base no SKU
UPDATE produto SET grupo = 'LINHA PIRULITO GLUBPOP' WHERE sku = '450';
UPDATE produto SET grupo = 'LINHA PIRULITO GLUBPOP' WHERE sku = '451';
UPDATE produto SET grupo = 'LINHA PIRULITO GLUBPOP' WHERE sku = '452';
UPDATE produto SET grupo = 'LINHA PIRULITO GLUBPOP' WHERE sku = '453';
UPDATE produto SET grupo = 'LINHA RECHEADOS GLUB' WHERE sku = '560';
UPDATE produto SET grupo = 'LINHA RECHEADOS GLUB 80 GR' WHERE sku = '561';
UPDATE produto SET grupo = 'LINHA RECHEADOS GLUB 80 GR' WHERE sku = '562';
UPDATE produto SET grupo = 'LINHA RECHEADOS GLUB 80 GR' WHERE sku = '563';
UPDATE produto SET grupo = 'LINHA RECHEADOS GLUB 80 GR' WHERE sku = '564';
UPDATE produto SET grupo = 'LINHA RECHEADOS GLUB' WHERE sku = '565';
UPDATE produto SET grupo = 'LINHA RECHEADOS GLUB 80 GR' WHERE sku = '567';
UPDATE produto SET grupo = 'LINHA RECHEADOS GLUB 80 GR' WHERE sku = '568';
UPDATE produto SET grupo = 'LINHA RECHEADOS GLUB' WHERE sku = '570';
UPDATE produto SET grupo = 'LINHA RECHEADOS GLUB' WHERE sku = '575';
UPDATE produto SET grupo = 'LINHA RECHEADOS GLUB' WHERE sku = '580';
UPDATE produto SET grupo = 'LINHA RECHEADOS GLUB' WHERE sku = '585';
UPDATE produto SET grupo = 'LINHA GRANEL' WHERE sku = '1465';
UPDATE produto SET grupo = 'LINHA GRANEL' WHERE sku = '1815';
UPDATE produto SET grupo = 'LINHA GRANEL' WHERE sku = '1821';
UPDATE produto SET grupo = 'SABORELLE' WHERE sku = '2200';
UPDATE produto SET grupo = 'SABORELLE' WHERE sku = '2210';
UPDATE produto SET grupo = 'LINHA COBERTOS DE CHOCOLATE - SAGRA' WHERE sku = '2252';
UPDATE produto SET grupo = 'LINHA COBERTOS DE CHOCOLATE - SAGRA' WHERE sku = '2269';
UPDATE produto SET grupo = 'LINHA COBERTOS DE CHOCOLATE - SAGRA' WHERE sku = '2275';
UPDATE produto SET grupo = 'LINHA COBERTOS DE CHOCOLATE - SAGRA' WHERE sku = '2281';
UPDATE produto SET grupo = 'LINHA PALITOS COBERTOS' WHERE sku = '2298';
UPDATE produto SET grupo = 'SABORELLE' WHERE sku = '2400';
UPDATE produto SET grupo = 'SABORELLE' WHERE sku = '2410';
UPDATE produto SET grupo = 'LINHA PALITOS COBERTOS' WHERE sku = '2510';
UPDATE produto SET grupo = 'LINHA ROSCAS SAGRA' WHERE sku = '2730';
UPDATE produto SET grupo = 'LINHA ROSCAS SAGRA' WHERE sku = '2740';
UPDATE produto SET grupo = 'LINHA ROSCAS SAGRA' WHERE sku = '2803';
UPDATE produto SET grupo = 'LINHA ROSCAS SAGRA' WHERE sku = '2810';
UPDATE produto SET grupo = 'LINHA ROSCAS SAGRA' WHERE sku = '2826';
UPDATE produto SET grupo = 'LINHA ROSCAS SAGRA' WHERE sku = '2832';
UPDATE produto SET grupo = 'LINHA ROSCAS SAGRA' WHERE sku = '2849';
UPDATE produto SET grupo = 'LINHA BEIJO DE MEL' WHERE sku = '2870';
UPDATE produto SET grupo = 'LINHA BEIJO DE MEL' WHERE sku = '2871';
UPDATE produto SET grupo = 'LINHA BEIJO DE MEL' WHERE sku = '2872';
UPDATE produto SET grupo = 'LINHA BEIJO DE MEL' WHERE sku = '2873';
UPDATE produto SET grupo = 'LINHA BEIJO DE MEL' WHERE sku = '2874';
UPDATE produto SET grupo = 'LINHA BEIJO DE MEL' WHERE sku = '2875';
UPDATE produto SET grupo = 'LINHA ROSCAS SAGRA' WHERE sku = '2910';
UPDATE produto SET grupo = 'LINHA ROSCAS SAGRA' WHERE sku = '2920';
UPDATE produto SET grupo = 'LINHA SALKIM' WHERE sku = '2938';
UPDATE produto SET grupo = 'LINHA SALKIM' WHERE sku = '2944';
UPDATE produto SET grupo = 'LINHA SALKIM' WHERE sku = '2951';
UPDATE produto SET grupo = 'LINHA SALKIM' WHERE sku = '2960';
UPDATE produto SET grupo = 'LINHA SALKIM' WHERE sku = '2965';
UPDATE produto SET grupo = 'LINHA BEIJO DE MEL COBERTOS' WHERE sku = '3200';
UPDATE produto SET grupo = 'LINHA BEIJO DE MEL COBERTOS' WHERE sku = '3201';
UPDATE produto SET grupo = 'LINHA BEIJO DE MEL COBERTOS' WHERE sku = '3202';
UPDATE produto SET grupo = 'LINHA FOOD SERVICE' WHERE sku = '3310';
UPDATE produto SET grupo = 'LINHA FOOD SERVICE' WHERE sku = '3320';
UPDATE produto SET grupo = 'LINHA FOOD SERVICE' WHERE sku = '3340';
UPDATE produto SET grupo = 'LINHA FOOD SERVICE' WHERE sku = '3350';
UPDATE produto SET grupo = 'LINHA FOOD SERVICE' WHERE sku = '3360';
UPDATE produto SET grupo = 'LINHA COBERTOS DE CHOCOLATE - SAGRA' WHERE sku = '3550';
UPDATE produto SET grupo = 'OVOS' WHERE sku = '3600';
UPDATE produto SET grupo = 'OVOS' WHERE sku = '3700';
UPDATE produto SET grupo = 'SABORELLE' WHERE sku = '4955';
UPDATE produto SET grupo = 'SABORELLE' WHERE sku = '4956';
UPDATE produto SET grupo = 'LINHA SALKIM' WHERE sku = '5671';
UPDATE produto SET grupo = 'LINHA COBERTOS DE CHOCOLATE - GLUB' WHERE sku = '6510';
UPDATE produto SET grupo = 'SABORELLE' WHERE sku = '6600';
UPDATE produto SET grupo = 'LINHA ROSQUINHA 50 GRS' WHERE sku = '7700';
UPDATE produto SET grupo = 'LINHA ROSQUINHA 50 GRS' WHERE sku = '7850';
