whatsapp.api.url=${WHATSAPP_API_URL:https://graph.facebook.com/v23.0}
whatsapp.phone-number-id=${WHATSAPP_PHONE_NUMBER_ID:SEU_PHONE_NUMBER_ID}
whatsapp.access-token=${WHATSAPP_ACCESS_TOKEN:SEU_TOKEN}

# Autenticação básica para proteger o endpoint /whatsapp/teste
whatsapp.api.user=${WHATSAPP_API_USER:admin}
whatsapp.api.password=${WHATSAPP_API_PASSWORD:admin}

# Banco de dados PostgreSQL (salesrep/salesrep_new)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/salesrep_new}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=validate

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
spring.flyway.out-of-order=true
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Para banco de dados não existente
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}

spring.web.error.include-stacktrace=never

# JWT
jwt.secret=${JWT_SECRET:3fK8!pL9#tVqZ7xW2@hN5$uB1^cR6yD0}
jwt.expiration-ms=3600000

# Logging de segurança
logging.level.org.springframework.security=DEBUG

# Origens permitidas para o CORS
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}

# Habilitar ou desabilitar proteção CSRF
app.security.csrf.enabled=${APP_SECURITY_CSRF_ENABLED:true}

